version: '3.8'

services:
  jenkins-backend:
    build: ./back-end
    container_name: jenkins-connectaid-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./back-end:/app
      - uploads_data:/app/uploads
    env_file:
      - ./back-end/.env
    networks:
      - jenkins-connectaid-network

  jenkins-frontend:
    build: ./front-end
    container_name: jenkins-connectaid-frontend
    restart: unless-stopped
    ports:
      - "81:80"
    depends_on:
      - jenkins-backend
    volumes:
      - ./front-end:/app/code
    networks:
      - jenkins-connectaid-network

networks:
  jenkins-connectaid-network:
    driver: bridge

volumes:
  uploads_data:
    driver: local
