version: '3.8'

services:
  cicd-backend:
    build: ./back-end
    container_name: cicd-connectaid-backend
    restart: unless-stopped
    ports:
      - "5002:5000"
    volumes:
      - ./back-end:/app
      - uploads_data:/app/uploads
    env_file:
      - ./back-end/.env
    networks:
      - cicd-connectaid-network

  cicd-frontend:
    build: ./front-end
    container_name: cicd-connectaid-frontend
    restart: unless-stopped
    ports:
      - "82:80"
    depends_on:
      - cicd-backend
    volumes:
      - ./front-end:/app/code
    networks:
      - cicd-connectaid-network

networks:
  cicd-connectaid-network:
    driver: bridge

volumes:
  uploads_data:
    driver: local 