version: '3.8'

services:
  backend:
    build: ./back-end
    container_name: connectaid-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./back-end:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://your_mongodb_atlas_uri
      - JWT_SECRET=your_jwt_secret_key
    networks:
      - connectaid-network

  frontend:
    build: ./front-end
    container_name: connectaid-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - connectaid-network

networks:
  connectaid-network:
    driver: bridge

volumes:
  uploads_data:
    driver: local 